### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by eserte** [perlwasm/Wasm#22] opened 2020-04-12 06:16 UTC
Usually my cpan test+install wrapper runs with limited datasize (on Linux 3GB, on FreeBSD 1GB). This seems to cause test failures like this: http://www.cpantesters.org/cpan/report/7e96e430-7c45-11ea-b200-2322ffe2237e (which is not from one of my smoker boxes, so other systems have this problem, too).

**Comment by plicease** [comment] 2020-04-12 12:27
Ah thanks for the report.  I saw reports that looks like they were coming from identical configurations just minutes apart and couldn't figure out why one was passing and one was failing.

Unfortunately I am still not able to reproduce this.  When I set the datasize to 40M the test suite still runs for me okay.  If I set it much lower than that it won't even run `cpanm`.

https://gist.github.com/plicease/58e01cbe68f00d0781fa0c1d5d7a0252

Can I see the test+install wrapper?  Possibly I am not using limit correctly?

**Comment by eserte** [comment] 2020-04-12 13:00
Here's the script: https://github.com/eserte/srezic-misc/blob/127d3e2c7dc58ed15aa925a199c4ed004936fd13/scripts/cpan_smoke_modules#L1593
Depending on operating system and availability of tools, either the command `limits` or perl's `BSD::Resource` is used.

**Comment by plicease** [comment] 2020-04-12 13:59
I was able to reproduce by setting `vmemoryuse`, and also with the wasmtime cli, so I don't think this is an actual issue with the Perl bindings.  I've opened an issue with the upstream project, hopefully they can enlighten me on a fix or a workaround.

Question: there is a comment that `-v` is necessary for FreeBSD, do you need it for Liniux?  Setting just the datasize limit doesn't seem to OOM Linux.

**Comment by eserte** [comment] 2020-04-12 14:05
None of my linux systems have `limits` available, so they go all the `BSD::Resource` path and using `RLIMIT_AS` there (the comment here says that "linux does not honor RLIMIT_DATA").

**Comment by plicease** [comment] 2020-04-12 17:57
I got some feedback from the Wasmtime folks.  From googling around it sounds like `RLIMIT_AS` is the same as bash `ulimit -v`, which is why I was able to reproduce that way.  TL;DR is that `ulimit -v` limits the virtual address size, which includes large `PROT_NONE` pages which are used I think by Wasmtime to detect OOB memory errors.  From what I understand these pages don't consume actual resources.

Helpful reading:
https://docs.google.com/document/d/17y4kxuHFrVxAiuCP_FFtFA2HP5sNPsCD10KEx17Hz6M/edit
https://lwn.net/Articles/428100/

(The second article concerns Go, which uses `PROT_NONE` pages a little differently, but the discussion is useful).

It would be good if the configuration could be changed because limiting virtual address space (rather than actual virtual memory used) is not quite what you want.  On the other hand I don't think `ulimit -m` is what you want either, so I am not sure what the best course of action is.  I certainly appreciate your reports, but they will of limited use as currently configured.

**Comment by eserte** [comment] 2020-04-12 18:39
Starting with 1.2.2, things look better: http://matrix.cpantesters.org/?dist=Mojolicious-Plugin-Prometheus%201.2.2
Closing issue.

**Comment by eserte** [comment] 2020-04-12 18:48
Interesting readings.

My plan so far is: set only soft limits in `cpan_smoke_modules`, and write CPAN distroprefs for specific modules which need higher memory limits. The distroprefs file would do something like `limits -v 16G make test` for FreeBSD and something equivalent for Linux.

**Comment by plicease** [comment] 2020-04-12 19:27
Essentially any module that uses `Wasm` (the Perl dist) is going to need a higher limit.  Would you be able to key off of a dependency, because it could get tedious adding a distro pref for each dependency (assuming this module takes off).

It would be useful for `Wasm` or maybe even `Alien::wasmtime` to detect the lower limit at least warn with an appropriate diagnostic, or maybe even refuse to install

**Comment by plicease** [comment] 2020-04-12 20:09
Setting `ulimit -v` doesn't seem to cause OOM failure on macOS, which suggests that the accounting on macOS is smarter.

**Comment by eserte** [comment] 2020-04-12 20:09
> Essentially any module that uses Wasm (the Perl dist) is going to need a higher limit. Would you be able to key off of a dependency, because it could get tedious adding a distro pref for each dependency (assuming this module takes off).

Yes, it would be tedious. Unfortunately, the wrapper is just a wrapper around CPAN.pm, and all the dependency handling is invisible to it. Another idea would be to write a CPAN.pm plugin which does the memory limiting --- the plugin would at least see the first-level dependencies. But for more levels it would also have to use other sources, maybe deps.cpantesters.org

> It would be useful for Wasm or maybe even Alien::wasmtime to detect the lower limit at least warn with an appropriate diagnostic, or maybe even refuse to install

Firefox::Marionette does this at configuration time. This is causing UNKNOWN reports on my smokers. I usually see this, and run the smokers manually without the limits to generate PASS reports.

**Comment by eserte** [comment] 2020-04-12 20:37
I am considering to drop the memory limiting completely on my VMs. The limit was added to the wrapper script in 2007 when my smoker system was my workstation --- and misbehaving CPAN modules were really disturbing in my regular work. Nowadays all my smokers run on dedicated VMs, so the worst effect would be a dead VM which could be rebooted.

**Comment by plicease** [comment] 2020-04-12 22:24
> Firefox::Marionette does this at configuration time. This is causing UNKNOWN reports on my smokers. I usually see this, and run the smokers manually without the limits to generate PASS reports.

Ah thanks for pointing me to the prior art that will be a good place to start.

> I am considering to drop the memory limiting completely on my VMs. The limit was added to the wrapper script in 2007 when my smoker system was my workstation --- and misbehaving CPAN modules were really disturbing in my regular work. Nowadays all my smokers run on dedicated VMs, so the worst effect would be a dead VM which could be rebooted.

Certainly would be easier from my end :)  I was wondering if VMs were being used if memory limits could be implemented there.

It does seem as though this might be a Linux only issue, I wasn't able to reproduce on macOS.  I suspect FreeBSD might be similar (they don't have FreeBSD binaries unfortunately for Wasmtime).  For now I am only testing on Linux + macOS + Windows since that is what the Wasmtime project provides as binaries.

As you pointed out there are other cpantesters with similar limits I'll still want to have some kind of diagnostic when configure sees a ulimit it doesn't like.

Please let me know if there is anything that I can do on my end to make this easier.

**Comment by plicease** [comment] 2020-05-07 19:40
I think this has been solved as well as it can be, and there are caveats in the documentation discussing the issues involved at this point so I am closing this.

I really appreciate the report and the engagement on this issue it has helped a lot.

**Closed as completed by plicease** 2020-05-07 19:40 UTC

**Comment by eserte** [comment] 2022-11-04 20:40
FYI: My Fedora 36 smoker started again to send fail reports. It's because there was a problem with another CPAN distribution crashing this VM, and me not remembering this discussion and activating again a memlimit on this VM. Now there's a distropref active for that distribution, and the memlimit is gone again.

**Comment by plicease** [comment] 2022-11-04 21:54
> FYI: My Fedora 36 smoker started again to send fail reports. It's because there was a problem with another CPAN distribution crashing this VM, and me not remembering this discussion and activating again a memlimit on this VM. Now there's a distropref active for that distribution, and the memlimit is gone again.

Thanks for the heads up!
